import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outDir = resolve(__dirname, '../src/css')
const outFile = resolve(outDir, 'tokens.css')

mkdirSync(outDir, { recursive: true })

// CSS output is populated as primitive and semantic tokens are defined (TOKEN-02/03 onward)
const css = [
  '/* @resovo/design-tokens — generated by scripts/build-css.ts, do not edit manually */',
  ':root {',
  '  /* primitives and semantic tokens will be emitted here */',
  '}',
  '',
].join('\n')

writeFileSync(outFile, css, 'utf-8')
console.log(`design-tokens: wrote ${outFile}`)
