import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { colors } from '../src/primitives/color.js'
import { space } from '../src/primitives/space.js'
import { size } from '../src/primitives/size.js'
import { radius } from '../src/primitives/radius.js'
import { typography } from '../src/primitives/typography.js'
import { motion } from '../src/primitives/motion.js'
import { shadow } from '../src/primitives/shadow.js'
import { zIndex } from '../src/primitives/z-index.js'

const __dirname = dirname(fileURLToPath(import.meta.url))

type TokenLeaf = string | number
type TokenTree = Record<string, unknown>

const PREFIX_MAP: Record<string, string> = {
  colors: 'color',
  space: 'space',
  size: 'size',
  radius: 'radius',
  shadow: 'shadow',
  zIndex: 'z',
  'typography.fontSize': 'font-size',
  'typography.lineHeight': 'line-height',
  'typography.fontWeight': 'font-weight',
  'typography.fontFamily': 'font-family',
  'motion.duration': 'duration',
  'motion.easing': 'easing',
}

function toKebab(key: string): string {
  return key
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/\./g, '-')
    .toLowerCase()
}

function flatten(node: unknown, path: string[], out: Array<[string, string]>): void {
  if (node === null || node === undefined) return
  if (typeof node === 'string' || typeof node === 'number') {
    const varName = `--${path.map(toKebab).join('-')}`
    out.push([varName, String(node)])
    return
  }
  if (typeof node === 'object') {
    for (const [key, value] of Object.entries(node as TokenTree)) {
      flatten(value, [...path, key], out)
    }
  }
}

function buildGroup(rootKey: string, node: unknown): Array<[string, string]> {
  const out: Array<[string, string]> = []
  if (node === null || typeof node !== 'object') return out

  for (const [key, value] of Object.entries(node as TokenTree)) {
    const nestedPath = `${rootKey}.${key}`
    if (PREFIX_MAP[nestedPath]) {
      const prefix = PREFIX_MAP[nestedPath]
      const leaves: Array<[string, string]> = []
      flatten(value, [], leaves)
      for (const [leaf, v] of leaves) {
        const suffix = leaf.replace(/^--/, '')
        out.push([suffix ? `--${prefix}-${suffix}` : `--${prefix}`, v])
      }
    } else if (PREFIX_MAP[rootKey]) {
      const prefix = PREFIX_MAP[rootKey]
      const leaves: Array<[string, string]> = []
      flatten(value, [key], leaves)
      for (const [leaf, v] of leaves) {
        const suffix = leaf.replace(/^--/, '')
        out.push([`--${prefix}-${suffix}`, v])
      }
    }
  }
  return out
}

function buildCss(): string {
  const sources: Array<[string, unknown]> = [
    ['colors', colors],
    ['space', space],
    ['size', size],
    ['radius', radius],
    ['shadow', shadow],
    ['zIndex', zIndex],
    ['typography', typography],
    ['motion', motion],
  ]

  const allVars: Array<[string, string]> = []
  for (const [rootKey, node] of sources) {
    allVars.push(...buildGroup(rootKey, node))
  }

  const body = allVars.map(([k, v]) => `  ${k}: ${v};`).join('\n')
  return `/* AUTO-GENERATED by scripts/build-css.ts — DO NOT EDIT */\n:root {\n${body}\n}\n`
}

function main(): void {
  const outDir = resolve(__dirname, '../src/css')
  const outFile = resolve(outDir, 'tokens.css')
  mkdirSync(outDir, { recursive: true })
  const css = buildCss()
  writeFileSync(outFile, css, 'utf-8')
  console.log(`[design-tokens] wrote ${outFile} (${css.split('\n').length} lines)`)
}

main()
